---
#- src: https://github.com/cycloidio/ansible-cron
#  version: master
#  name: cycloid.cron
#  scm: git

#- src: https://github.com/cycloidio/ansible-postfix
#  version: master
#  name: cycloid.postfix
#  scm: git

- src: https://github.com/cycloidio/ansible-php
  version: master
  name: cycloid.php
  scm: git

- src: https://github.com/jdauphant/ansible-role-nginx
  name: jdauphant.nginx
  scm: git

- src: https://github.com/cycloidio/ansible-deployment
  name: cycloid.deployment
  scm: git

- src: https://github.com/cycloidio/ansible-customer-ssh
  version: master
  name: cycloid.customer-ssh
  scm: git

- src: https://github.com/cycloidio/ansible-telegraf
  version: master
  name: cycloid.telegraf
  scm: git

- src: https://github.com/dj-wasabi/ansible-telegraf
  version: master
  name: dj-wasabi.telegraf
  scm: git

- src: https://github.com/cycloidio/ansible-base-aws
  version: master
  name: cycloid.base-aws
  scm: git

- src: https://github.com/cycloidio/ansible-fluentd
  version: master
  name: cycloid.fluentd
  scm: git
